spring:
  batch:
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:~/test'
    username: sa
    password: sa
logging:
  config: classpath:log4j2/log4j2-dev.xml
